### ISSUE TITLE
BUG: User is not mentioned when attempting to reserve a slot already reserved

### ISSUE THREAD

**Issue by Uncle-Sagbag** [sesounit/Kakapo#65]
A new user joined the server and used the roster believing they were reserved for a role. However, that role was already taken. The only feedback they received was the following message in #bot-commands:

> Please remove the person from this slot before trying to claim it.

I suggest a new format, that would be the following.

> <@mention> cannot take slot <role ID> because it is already taken by someone else.

By mentioning them and the slot they attempted to reserve, they will be informed that their attempt was not successful.

Additionally, all error messages should be ping mentions and all success messages should be silent mentions.

**Comment by Pickle423** [comment]
issued resolved in pull request #66
