### ISSUE TITLE
BUG: remindFeedback outdated since new Feedback Form

### ISSUE THREAD

**Issue by Uncle-Sagbag** [sesounit/Kakapo#69]
As the name implies, the !remindFeedback command is no longer accurate and outdated due to the new Feedback Form.

Ideally, I would like the command to be working as before: it would DM the Host a list of operatives who were on the Roster but did not fill out the form. With the new Feedback Form it may be more difficult to acquire a list of people who did and did not use the form. I rely on your expertise to figure that out.

If this bug is, for whatever reason, unfixable, I would like the command removed.

**Comment by Pickle423** [comment]
Fixed in pull request #71
