### ISSUE TITLE
Feature Request: Add total reservation count to roster

### ISSUE THREAD

**Issue by Uncle-Sagbag** [sesounit/Kakapo#76]
# User Story
As a host, I want to quickly determine the total count of people coming to my operation so I can prepare it accordingly.

As a COO, I want to quickly determine the total count of people in an operation so I can enter it to the SESO Operation Stats sheet.

# Acceptance Criteria

1. Add a "Total Reservations:" counter at the bottom of the roster that updates every time someone reserves or unreserved a slot

**Comment by Pickle423** [comment]
Added in #78
